_episodes/01-introduction.md
@sstevens2 sparked my interest in this material (I'll be teaching it in April) and I did a rewrite of the opening. :) More changes/suggestions to come. 
I did cut a lot of the more technical details (maybe too much?) so feedback is welcome. 
~Also, don't merge yet, I want to add at least one more analogy Sarah shared about images vs containers!~
=> Reorganizing intro material

_episodes/01-introduction.md
removing notes about being the first time the course ran and that it only looks like a proper carpentry lesson
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson …
=> More professional look disclaimers section

_episodes/04-docker-hub.md
=> Docker Hub changes

README.md
This PR updates the lesson title to include the container technology to match with the approach used in the [singularity-introduction](https://github.com/carpentries-incubator/singularity-introduction) repository. Resolves issue #27.
=> Updated lesson title based on discussion in #27

_episodes/08-reproducibility.md
The current version of the lesson has lots of excellent material on using Docker but when we initially ran a workshop using the lesson we thought that there was a gap where we needed to cover how you can use Docker containers to enable reproducibility. This episode is our attempt at producing material to cover that gap.
=> adds episode discussing how to enable reproducible use of containers

README.md, index.md
not necessary, but I thought it might be nice to link to the singularity lesson so folks know about it.
=> adding links to singularity lesson

_config.yml
synchronize with README change made in #29
=> changing lesson title to include Docker

_episodes/05b-advanced-containers.md
=> Issue 44 05b

_episodes/08-reproducibility.md
=> Fixed formatting of titles of advantages-/disadvantages-lists

_episodes/08-reproducibility.md
as discussed by @sstevens2 and I after the workshop today. 😁
=> adding closing reflective exercise

.gitpod.Dockerfile, .gitpod.yml, README.md
For easy lesson review and maintenance in the web.
=> Adding gitpod

_episodes/07-containers-for-continuous-integration.md, index.md
=> removing container-playground references

_episodes/05b-advanced-containers.md
this was suggested as a better cross platform solution
Related to issue #64
=> updating pwd variable

README.md
Fixes #49
Quick fix I should have done long ago.  @aturner-epcc @ChristinaLK and @jcohen02 please review.
=> Adding additional maintainers

_episodes/05b-advanced-containers.md
=> Edit language so it doesn't assume the dockerfile exists

index.md
This PR adds the previously discussed learner profiles. Closes #86
=> Adds learner profiles. Closes #86

setup.md
Propose changes in setup instructions made when I ran a recent workshop, merged with improvements already made to the main repository.
=> Dme26 2020 09 update setup

AUTHORS, _episodes/01-introduction.md, _episodes/02-meet-docker.md, _episodes/03-running-containers.md, _episodes/04-docker-hub.md, _episodes/04b-managing-containers.md, _episodes/05-creating-container-images.md
Attempt to address issue #85 with miscellaneous editing
=> feat: Updated and clarified motivations

_episodes/03-running-containers.md
=> Adding hint about using /proc/version to see Linux version

_episodes/04-docker-hub.md
=> Adding "green flags" for DockerHub containers

_extras/e01-github-actions.md
got sidetracked, haha. 
This still needs a fair bit of polishing, but is hopefully a bit clearer now.
=> Adding transition sentences to the github actions extra

_episodes/05b-advanced-containers.md
=> adding callout for common docker run flags

index.md
The utility of highlighting laptop focus also relates to the discussions on #70 .
=> Clarify on-laptop focus of lesson exercises

setup.md
I think Docker Desktop, along with WSL2, etc., has meant the Docker installation experience is much better than it was.
=> Convey more optimism regarding Docker installation

_episodes/07-docker-image-examples.md
This would be one way to resolve the conversation threads about Singularity + HPC centers.
=> adding note in application section about HPC

_episodes/05-creating-container-images.md, _episodes/07-docker-image-examples.md
Removing some stub content from view, to speed up preparation for use of material within workshops.
=> Structural clean up

_episodes/05-creating-container-images.md
Linux and its distributions all themselves have versions: reworded "versions" to match use of "distributions" elsewhere in lesson material.
=> Linux "distributions", not Linux "versions".

setup.md
A quick check welcomed as to whether my change makes the macOS instructions too complex to read (hopefully not).
=> macOS install: mention Homebrew and MacPorts

_episodes/01-introduction.md, _episodes/02-meet-docker.md, _episodes/03-running-containers.md, _episodes/04-docker-hub.md, _episodes/04b-managing-containers.md, _episodes/05-creating-container-images.md, _episodes/05b-advanced-containers.md, _episodes/07-docker-image-examples.md, _episodes/08-reproducibility.md, index.md
I tweaked presentation as I was working through the material for a recent workshop.
I hope that these changes aren't contentious, but that's also why I've grouped so many in this pull request...
=> Hopefully straightforward clean up

index.md
Noticed this in @ChristinaLK 's tour of the docker lesson in the recent discussion, so decided to put it in the objectives box.
=> putting objectives into special blockquote

_episodes/01-introduction.md, _episodes/02-meet-docker.md, _episodes/05-creating-container-images.md, _episodes/05b-advanced-containers.md, _episodes/07-docker-image-examples.md
Collecting together a number of tweaks and rewording that likely require checking and possible reworking.
Any suggested breaking up, reorganisation or other edits welcome!
=> Draft clarifications

_episodes/05b-advanced-containers.md
Prepping to teach this tomorrow and noticed that this version of the `Dockerfile` is in a different order than before.  Some might add the `COPY` line in the middle but think most would add it to the end.
=> Swapping order for consistency

_episodes/01-introduction.md
=> Container video

_episodes/02-meet-docker.md, _episodes/03-running-containers.md, _episodes/04-docker-hub.md, _episodes/04b-managing-containers.md, _episodes/05-creating-container-images.md, _episodes/05b-advanced-containers.md, _episodes/08-reproducibility.md
Updated the docker commands to follow the new CLI syntax.
Closes #133
=> Update to new CLI syntax

_episodes/05-creating-container-images.md
Closes #149 
May contain factual inaccuracies! please review!!
=> initial draft on build context

_episodes/03-running-containers.md
Prepping to teach and noticed that this exercise could use a little clarification.
=> Clarification about busybox x2

_episodes/03-running-containers.md
=> adding callout about rm and name flags"

setup.md
=> Add simple "docker version" to check the setup.

setup.md
=> Adds note on Git Bash issues

_episodes/introduction.md
=> Removes disclaimers

_episodes/advanced-containers.md
=> Adds security warning on secrets in containers

_episodes/advanced-containers.md, _extras/e01-github-actions.md, _extras/e02-jekyll-lesson-example.md
Moves material to more verbose `--mount` syntax. Closes #150
=> Adds updated mount syntax

_episodes/running-containers.md
=> Change busybox container to ubuntu

_extras/guide.md, index.md
Add learner pathway content into the instructor notes.
=> Add learner pathways into the instructor notes

_episodes/running-containers.md
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The …
=> Changed ubnutu to ubuntu

_episodes/introduction.md, _episodes/meet-docker.md, _extras/06-containers-on-the-cloud.md, _extras/08-orchestration.md
This PR fixes the heading levels in some of the episodes and the extra materials to address points raised by the editorial checks as part of the peer review process. See #195 for further information and https://github.com/carpentries-lab/reviews/issues/15 for the editor's comments.
Closes #195.
=> Fix headings as specified in editors comments for peer review

reference.md
=> Initial version of glossary. Closes #197

_episodes/creating-container-images.md
Fixes a broken link (to the next chapter) in the chapter titled **Creating Your Own Container Images**.
=> chore(cleanup): Fix broken link to relative file location

_episodes/advanced-containers.md
Faithful echo of exact error message for `sum.py`
=> chore: faithful echo of exact error message for sum.py

_episodes/advanced-containers.md
Use the new style of docker commands.
=> fix(cleanup): use the new style of docker commands

episodes/advanced-containers.md
This addresses #234. The questions now rather duplicate the objectives - not sure whether we want to update further but this does add some clarity as noted in the related issue.
Closes #234.
=> Updated questions at the start of "advanced containers"

episodes/reproduciblity.md
This PR provides various updates to the reproducibility section to address #231.
In the process, some other minor updates and typo fixes have also been made.
Closes #231.
=> Updates to the reproducibility section to address #231

episodes/introduction.md
Adds dependency definition as suggested by reviewer. Closes #201
=> Adds callout to define dependency. Closes #201
