_episodes/03-running-containers.md
_episodes/04b-managing-containers.md

- moving container management (ps, rm, etc. ) to its own episode, later. 
- adding material on running containers interactively, and with your own commands. You can't use `hello world` for this, so I've chosen `ubuntu`. Happy to use something else as needed. 
Not completely sold on yet: `docker pull` and then `docker run`. Maybe do `docker run hello-world` and then talk about `docker pull` when pulling 2nd container of choice? Or skip `hello world` altogether? 
Also, have NO idea if that table formatting is correct. That may be worth doing in html...
TO DO: 
- clean up formatting everywhere
- fix objectives/questions/keypoints

reworking container use episode

---

_episodes/02-meet-docker.md
_episodes/03-running-containers.md

Motivation for the changes:
1. The alpine commands were not producing the expected result.
2. `/proc/version` shows the identification of my host system instead of the docker container. Likely because `/proc` is partially mounted in the container.
3. `docker login` stores credentials unencrypted so adding a callout with a set of "better options" if one worries about this.

Address alpine issues and credentials security

---

_episodes/02-meet-docker.md

First PR from the updated version of this lesson that @jcohen02 and myself ran online in July 2020. This one does not have many changes, just some minor rewording. The example command used to check if Docker is running correct has been changed from `docker login` to `docker container ls` to avoid describing DockerHub at this point and to link with the initial commands that used in the next episode.

changes wording and examples slightly

---

_episodes/05-creating-container-images.md

Think this should fix #36.  
Looks like now `apk` doesn't have a general `python` package to install so you need to specify 2 or 3.  I changed the lesson to use `python3`.  When reviewing, please look out for uses of `python` that should be `python3` when building that container.  I did leave it `python`, instead of `python3`,  for the name of the container we make.

fixing apk python version issue

---

_episodes/05b-advanced-containers.md

Removes inconsistency when specifying the `-i` and `-t` flags to docker run in the "_Overriding the ENTRYPOINT_" section of `05b-advanced-containers.md`. This is referenced elsewhere as `-it` which is the general convention used to specify these flags.
As highlighted in issue #68 (thanks @markgdawson), there are a couple of instances where `-ti` has been used. These are fixed by this PR.

Remove inconsistency in use of -it flags in advanced containers.

---

_config.yml

In investigating #74, @drakeasberry and I discovered an issue with Episode 7, where running "the containers used in generating this lesson" gave the following error: `Jekyll::RemoteTheme::DownloadError`
As a fix, we now point Jekyll `remote_theme` (a parameter in `_config.yml`) to the main branch of the Carpentries GH pages theme.
#69 can be closed. This issue was resolved in [this commit](https://github.com/carpentries-incubator/docker-introduction/commit/d65409c189bec6d115318608c57cd6078f3a647f)
#74 can also be closed. This is the same issue that was resolved in the commit above
closes #74 #69

Resolve Theme Error in Jekyll Docker deployment (Ep.7)

---

_episodes/01-introduction.md
_episodes/07-containers-for-continuous-integration.md
_extras/guide.md
_includes/links.md
index.md
setup.md

This PR addresses issue #87, adding some text to the instructor notes in a new section "_Before teaching this lesson_" and a callout to the index page highlighting that differences can occur between the information shown in the lesson and the actual output/interface provided by Docker. Both new blocks of text invite either instructors or participants to highlight any problems they notice through opening a new issue.

Updating instructor notes and lesson front page re docker changes (Fixes #87)

---

_episodes/03-running-containers.md
_episodes/07-docker-image-examples.md
_extras/e02-jekyll-lesson-example.md

Hi all! 
This should close #85 and it also starts the option of having multiple different workflow examples of how to use Docker images in practice.  Feedback welcome!  I'd particularly like alternate titles and any additional information that you think is needed in the new `07-docker-image-examples.md` episode.
I also left a comment placeholder for a third example from @mkuzak on gdal+jupyter.  @mkuzak would you want to put in a PR to add that example once this one is merged? I think you've got a good start of what you could add to an extra's page and then link to the `07-docker-image-examples.md` episode.
Thanks!

Creating the "choose your own example(s)" episode

---

_episodes/02-meet-docker.md

Hi, this issue is related to #42.
I intend to also make a commit to Episode 03 in the `docker image` command, like mentioned in the issue. However, I preferred to keep changes to Episode 02 for this PR. I would appreciate some feedback on the challenge that was added; I wondered if it was adequate or if I should switch the command presented in the solution.
Summary of changes:
- Related to #42.
- Adds the 'Getting help' section.
- Adds the 'Exploring a command' challenge.
- Bumps Docker version in command output.
- Updates objectives and keypoints.
Thanks,
Vini

_episodes/02-meet-docker.md: add section on how to get help.

---

_extras/guide.md

Adding an example of where Linux hosts may behave differently to macOS and Windows hosts (and an extremely brief note as to why this occurs).

Linux hosts (vs mac/Win) may behave differently

---

CONTRIBUTING.md

Links now point to correct places: course git repository and the Carpentries Incubator website.
Just a small update with the with to the links in the CONTRIBUTING.md file

Fixed "Where to Contribute" links

---

_episodes/05b-advanced-containers.md

Adding a callout box to the end of the [advanced containers episode (05b)](https://github.com/carpentries-incubator/docker-introduction/blob/gh-pages/_episodes/05b-advanced-containers.md) highlighting the "[_10 Simple Rules for writing Dockerfiles for reproducible data science_](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008316) paper, as suggested in issue #128.

Add links to 10 simple dockerfile rules paper - closes #128

---

_episodes/advanced-containers.md

Reordered statements in v3 `Dockerfile` example in "_Creating More Complex Container Images_" in order to take effective advantage of layers. Thanks for highlighting this @MiddelkoopT, and suggesting the change.

Modify v3 Dockerfile example to take advantage of cache - closes #125

---

_episodes/advanced-containers.md

Fixes incorrect rendering of "Types of mounts" callout in advanced containers episode due to missing "callout" tag.
Closes #180.

Added missing callout tag in advanced containers episode

---

CITATION

This adds a suggested citation to the `CITATION` file which was previously empty.
This file should be updated to provide a complete [CFF](https://zenodo.org/record/1117789) file so this will need updating. However, to ensure we have some information on how to cite the repo, adding this for now.

Add CITATION file content

---

_extras/e02-jekyll-lesson-example.md

The current `jekyll:pages` container image fails due to a missing package. This PR selects the working `jekyll:3` container image instead which behaves as expected.

Updates name of jekyll container image, closes #190

---

LICENSE.md

This PR updates the text in LICENSE.md to address a comment in the pre-peer review editorial checks. See issue #196 and the reviewers comments in https://github.com/carpentries-lab/reviews/issues/15 for further details.
Closes #196.

Update licence to address editorial review comment

---

_extras/e01-github-actions.md
_extras/e02-jekyll-lesson-example.md

Updated the docker run command in the jekyll and github-actions examples to use the modern CLI usage style as described in the lesson [here](https://carpentries-incubator.github.io/docker-introduction/meet-docker/index.html#docker-command-line-interface-cli-syntax). Have tested the PR myself.

Updates the jekyll and github-actions examples to use the newer style of docker commands

---

_config.yml

This item was one of the issues brought up in the Carpentries lesson review checklist.
fixes #198

Updating the contact to the maintainer list

---

_episodes/docker-hub.md
_episodes/running-containers.md

Looks like the latest version of these lesson use the ubuntu container instead of busybox.
* For instance, ubuntu is used in the examples
* Therefore, we update the text in the relevant locations to reflect this

chore(typo): Replace busybox with ubuntu

---

_episodes/advanced-containers.md

In the section titled [The Importance of Command Order in a Dockerfile](https://carpentries-incubator.github.io/docker-introduction/advanced-containers/index.html#the-importance-of-command-order-in-a-dockerfile), the text states that:
>This order is important for rebuilding and you typically will want to put your RUN commands **before** your COPY commands.
> For example, in an instance where you wanted to copy multiply.py into the container image instead of sum.py. If the COPY line came before the RUN line, it would need to rebuild the whole image. If the COPY line came second then it would use the cached RUN layer from the previous build and then only rebuild the COPY layer.
In the example that introduces the `ENTRYPOINT` command, we currently have:
```Dockerfile
RUN apk add --update …
```

fix: Dockerfile command order in ENTRYPOINT example

---

episodes/docker-image-examples.md
episodes/introduction.md
episodes/meet-docker.md
episodes/reproduciblity.md

This PR adds exercise timing to the episodes that include exercises but didn't have exercise timing set previously.
For "Examples of Using Container Images in Practice" (`docker-image-examples.md`), there are no specific exercise callouts but the content suggests choosing one or more of the provided examples to practice using containers. I've therefore cut the "teaching" time to 10 minutes, assuming that the instructor will provide a brief overview of the different examples, and added 15 minutes exercise time. Perhaps it would even be better to increase this to 20 or 25 minutes? This is flexible since it depends on how much time the instructor wants to dedicate to this.
Closes #232.

Add exercise timing

---

index.md
profiles/learner-profiles.md

This PR addresses issue #225 relating to the target audience for the lesson:
- Adds a top-level "Target audience" box on the lesson intro page providing a brief note on the target audience.
- Copies the learner profiles content from the instructor notes section to the new learner profiles page in the workbench template.
- Adds some introductory text around the profiles content to ensure this is aimed at learners rather than instructors.
Closes #225

Add learner profiles content for workbench template

---

episodes/advanced-containers.md

This PR adds a solution to one of the questions towards the top of `advanced-containers.md`. The second question that didn't have a solution isn't really intended to have one since it highlights the question being answered in the next section of the material. To address this, the PR adds a note that the question is there as something to think about, with the answer worked through in the content below.
Closes #228.

Adding solution and guidance to questions in advanced-containers.md

---

episodes/introduction.md

This is a large and possibly controversial change to the introduction. I felt in particular that the "What is a Container? What is Docker?" section was too long and complicated by a few concepts that weren't strictly necessary. I've simplified it in the following ways:
* Remove paragraph about computer hardware. I didn't really see the relevance to containers, and this is a very long section that could benefit from some brevity
* Remove paragraph about computer filesystem. As above.
* Remove cat meme example. We actually already have some good concrete research motivations from the previous section  (Scientific Software Challenges), so I don't think an artificial example is needed here
* Separate section on docker from section on containers. This is nice natural way to split up this …

Rework definitions

---

episodes/introduction.md

Define docker

---

episodes/docker-hub.md

Improvement to objective wording as suggested by reviewer. Closes #229

Improves objective. Closes #229

---

episodes/creating-container-images.md

In relation to the disucssion in #209, this PR removes a left over reference to `cython` that could cause confusion for learners.

Remove outdated reference to cython

---

.github/workflows/sandpaper-main.yaml

As noted in the open issues:
https://github.com/carpentries/sandpaper/issues/605
and:
https://github.com/esciencecenter-digital-skills/geospatial-python/pull/128
The Github runner action in sandpaper-main.yaml needs to be pnned to Ubuntu 22.04 rather than ubuntu-latest for the lesson build process to work. This PR implements the required change.

Fix issue due to ubuntu-latest not containing R

---

.github/workflows/pr-receive.yaml

The markdown build workflow is failing on recent PRs. There seem to have been changes to this workflow in the main lesson template repo so this PR ports those changes into this repo.

Update PR receive action workflow
